<!DOCTYPE html>
<html ng-app="myapp">
<head>
    <meta charset="UTF-8"/>

    <title>Gogordos. Recomendación de restaurantes entre amigos. Restaurantes recomendados.</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="/assets/jquery/3.1.0/jquery.min.js"></script>

    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/assets/css/gogordos.css">

    <!-- For new restaurant page -->
    <script type="text/javascript" src="/assets/select2/4.0.3/select2.min.js"></script>
    <link rel="stylesheet" href="/assets/select2/4.0.3/select2.min.css">

    <!--  favicon-->
    <link rel="apple-touch-icon" sizes="57x57" href="/img/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/img/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/img/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/img/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/img/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/img/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/img/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/img/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/img/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/img/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/img/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicons/favicon-16x16.png">
    <link rel="manifest" href="/img/favicons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <script type="text/javascript" src="/assets/angular/angular.min.js"></script>
    <script type="text/javascript" src="/assets/angular/angular-ui-router.min.js"></script>
    <script type="text/javascript" src="/assets/angular/ngStorage.min.js"></script>

    <script type="text/javascript" src="/angular/app.js"></script>
    <script type="text/javascript" src="/angular/sign_up/sign_up_controller.js"></script>
    <script type="text/javascript" src="/angular/sign_up/account_box_controller.js"></script>
    <script type="text/javascript" src="/angular/login/login_controller.js"></script>
    <script type="text/javascript" src="/angular/services/focus.js"></script>
    <script type="text/javascript" src="/angular/account/account_controller.js"></script>
    <script type="text/javascript" src="/angular/restaurants/new_restaurant_controller.js"></script>
    <script type="text/javascript" src="/angular/user/user_page_controller.js"></script>
    <script type="text/javascript" src="/angular/home/home_controller.js"></script>
    <script type="text/javascript" src="/angular/user/add_friend_controller.js"></script>
    <script type="text/javascript" src="/angular/city/city_restaurants_controller.js"></script>
    <script type="text/javascript" src="/angular/restaurants/directives/restaurant_directive.js"></script>
    <script type="text/javascript" src="/angular/user/my_restaurants_controller.js"></script>


    <link rel="stylesheet" href="/assets/angular/ui-select/select.min.css">
    <script type="text/javascript" src="/assets/angular/ui-select/select.min.js"></script>
    <script type="text/javascript" src="/assets/angular/angular/1.5.8/angular-sanitize.js"></script>
    <!--
        IE8 support, see AngularJS Internet Explorer Compatibility http://docs.angularjs.org/guide/ie
        For Firefox 3.6, you will also need to include jQuery and ECMAScript 5 shim
      -->
    <!--[if lt IE 9]>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/es5-shim/2.2.0/es5-shim.js"></script>
    <script>
        document.createElement('ui-select');
        document.createElement('ui-select-match');
        document.createElement('ui-select-choices');
    </script>
    <![endif]-->

    <base href="/">

<!--    <base href="/">-->
</head>
<body>


<div class="container">

    <div class="row">
        <div class="col-md-9 ">

            <div ng-controller="AccountBoxController" class="header clearfix">
                <nav style="margin-top: 11px;">
                    <ul ng-if="loggedIn == true" class="nav nav-pills pull-right">
                        <li role="presentation"><a ui-sref="account()">{{ username }}</a></li>
                    </ul>

                    <ul ng-if="loggedIn == false" class="nav nav-pills pull-right">
                        <li role="presentation" class="active"><a ui-sref="signup({})">Regístrate</a></li>
                        <li role="presentation"><a ui-sref="login({})">Iniciar sesión</a></li>
                    </ul>

                </nav>
                <h3 class="text-muted"><a href="/">Gogordos</a> <span class="beta">Beta</span></h3>
            </div>

            <br>
            <br>
        </div>
    </div>

    <div class="row">
        <div class="col-md-9">
            <div ui-view></div>
        </div>
    </div>
</div> <!-- /container -->


<div id="footer">
    <div class="container">
        <p class="text-muted">Gogordos 2016 Barcelona. <a href="https://twitter.com/xabierlegasa">Contact</a>. Version <?= $version?></p>
    </div>
</div>

</body>
</html>
