---
- name: Deploy app to gogordos.net
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../../gogordos"
    ansistrano_deploy_to: "/var/www/gogordos"
    ansistrano_keep_releases: 5
    # There seems to be an issue with rsync in vagrant
    ansistrano_deploy_via: git
    ansistrano_git_repo: git@github.com:xabierlegasa/gogordos.git
    ansistrano_git_branch: master
    #ansistrano_git_identity_key_path: "../../../../Users/xabi/.ssh/xabi"
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }